2022-01-28 22:02:07,935 INFO    MainThread:23846 [wandb_setup.py:_flush():71] setting env: {}
2022-01-28 22:02:07,935 INFO    MainThread:23846 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-28 22:02:07,935 INFO    MainThread:23846 [wandb_init.py:_log_setup():371] Logging user logs to /mnt/disk1/duyna/FimiCalibIdea/wandb/run-20220128_220207-2p2u6lp9/logs/debug.log
2022-01-28 22:02:07,935 INFO    MainThread:23846 [wandb_init.py:_log_setup():372] Logging internal logs to /mnt/disk1/duyna/FimiCalibIdea/wandb/run-20220128_220207-2p2u6lp9/logs/debug-internal.log
2022-01-28 22:02:07,936 INFO    MainThread:23846 [wandb_init.py:init():404] calling init triggers
2022-01-28 22:02:07,937 INFO    MainThread:23846 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {'metric': 'mse', 'early_stop': 50, 'ssa': False, 'train_type': 'train', 'name': 'Singlecalib', 'data_mean': array([14.78165346, 17.64072122]), 'data_std': array([3.5851945 , 3.57261641])}
2022-01-28 22:02:07,937 INFO    MainThread:23846 [wandb_init.py:init():460] starting backend
2022-01-28 22:02:07,937 INFO    MainThread:23846 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-01-28 22:02:08,014 INFO    MainThread:23846 [backend.py:ensure_launched():216] starting backend process...
2022-01-28 22:02:08,090 INFO    MainThread:23846 [backend.py:ensure_launched():221] started backend process with pid: 5170
2022-01-28 22:02:08,092 INFO    MainThread:23846 [wandb_init.py:init():469] backend started and connected
2022-01-28 22:02:08,097 INFO    MainThread:23846 [wandb_init.py:init():533] updated telemetry
2022-01-28 22:02:08,301 INFO    MainThread:23846 [wandb_init.py:init():563] communicating current version
2022-01-28 22:02:09,387 INFO    MainThread:23846 [wandb_init.py:init():568] got version response 
2022-01-28 22:02:09,387 INFO    MainThread:23846 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-01-28 22:02:09,906 INFO    MainThread:23846 [wandb_init.py:init():606] starting run threads in backend
2022-01-28 22:02:14,346 WARNING MainThread:23846 [wandb_init.py:init():952] interrupted
Traceback (most recent call last):
  File "/home/aiotlab/anaconda3/envs/thanhnt_vaipe/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 931, in init
    run = wi.init()
  File "/home/aiotlab/anaconda3/envs/thanhnt_vaipe/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 611, in init
    _ = backend.interface.communicate_run_start(run_obj)
  File "/home/aiotlab/anaconda3/envs/thanhnt_vaipe/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 221, in communicate_run_start
    result = self._communicate_run_start(run_start)
  File "/home/aiotlab/anaconda3/envs/thanhnt_vaipe/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 423, in _communicate_run_start
    result = self._communicate(rec)
  File "/home/aiotlab/anaconda3/envs/thanhnt_vaipe/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/aiotlab/anaconda3/envs/thanhnt_vaipe/lib/python3.9/site-packages/wandb/sdk/interface/router.py", line 37, in get
    is_set = self._object_ready.wait(timeout)
  File "/home/aiotlab/anaconda3/envs/thanhnt_vaipe/lib/python3.9/threading.py", line 574, in wait
    signaled = self._cond.wait(timeout)
  File "/home/aiotlab/anaconda3/envs/thanhnt_vaipe/lib/python3.9/threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
